ci:
    skip: [fmt]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml
      - id: check-shebang-scripts-are-executable
        exclude: '\.rs$'
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: detect-private-key
  - repo: https://gitlab.com/bmares/check-json5
    rev: v1.0.0
    hooks:
    - id: check-json5
  - repo: https://github.com/crate-ci/typos
    rev: v1.29.5
    hooks:
      - id: typos
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.23.3
    hooks:
      - id: gitleaks
  - repo: https://github.com/backplane/pre-commit-rust-hooks
    rev: v1.1.0
    hooks:
      - id: fmt
