name: Continuous Integration

on:
  push:
    paths-ignore:
      - "**/README.md"
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  rust-checks:
    name: Rust Checks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        action:
          - command: build
            args: --release
            package: your-life-in-x
          - command: build
            args: --release
            package: simulation
          - command: build
            args: --release
            directory: esp
          - command: fmt
            args: --all -- --check --color always
          - command: clippy
            args: --all-features --workspace -- -D warnings
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          target: riscv32imc-unknown-none-elf
          toolchain: stable
          components: rust-src, rustfmt, clippy

      - name: Enable caching
        uses: Swatinem/rust-cache@v2

      - name: Run command
        run: |
          if [[ -n "${{ matrix.action.package }}" ]]; then
            cargo ${{ matrix.action.command }} --package ${{ matrix.action.package }} ${{ matrix.action.args }}
          elif [[ -n "${{ matrix.action.directory }}" ]]; then
            cd ${{ matrix.action.directory }} && cargo ${{ matrix.action.command }} ${{ matrix.action.args }}
          else
            cargo ${{ matrix.action.command }} ${{ matrix.action.args }}
          fi
